### ISSUE TITLE
Using generic types to improve type inference

### ISSUE THREAD

**Issue by acdbaykal** [sergiofasilva/memoizeit#5]
Hello,

I stumbled upon this repo while working on my personal typescript project. While using `memoizeit` I discovered that I lose the functions' type signature.  Evey memoized function becomes `(...args: any[]) => any`, which is realy not that good tbh. You can improve the type signature if you replace types/index.d.ts with

```typescript
export = memoizeit;
function memoizeit<Args extends unknown[], Out>(func: (...args: Args) => Out): (...args: Args) => Out;

```

This way typescript can infer the function signatures correctly. 

Have a good one,
Ali

**Comment by sergiofasilva** [comment]
Hi Ali (@acdbaykal),
Thank you for your interest and your suggestion for improvement.
Typescript isn't really my thing.

Would you like to submit a PR (pull request) with your suggestion? I would be happy to accept your contribution.

Regards, 
Sergio

**Comment by sergiofasilva** [comment]
Fixed.
